### ISSUE TITLE
Direction up issue

### ISSUE THREAD

**Issue by rogomantik** [Boris-Em/Cloudy#1]
I run the sample without changes and there is a problem with the upward direction.
In the screenshot occurs 1 time but it also happens several times. in both orientations

![img](https://cloud.githubusercontent.com/assets/1736768/17398523/848055bc-5a3d-11e6-8f36-9c1af28f7f94.jpg)

**Comment by Boris-Em** [comment]
Hi @rogomantik, 
Thank you for opening this issue! Would you mind telling me which device I can use to reproduce it?
I haven't be able to so far.
Thanks!

**Comment by rogomantik** [comment]
Hi,
I tested it only on the iPhone Simulator 6s iOS 9.3
Rotate the screen and press reload some times and should occur
This is a screenshot when in vertical mode
![test](https://cloud.githubusercontent.com/assets/1736768/17642468/acd81f92-6148-11e6-9acf-2daf9201b158.png)
The shadow follows the curve but, above, is drawn a white area
